#+title: Python-Powered SQLite Database for AntArchitecture Community Data
#+author: Antoine Hermant

This Python module provides an efficient SQLite database for browsing, visualizing and processing Internal Reflecting Horizons (isochrones) across Antarctica, curated by the AntArchitecture action group. It is specifically designed for ice dynamic modelers who need a fast, memory-efficient data structure to constrain their models. Have a look at the [[https://antoinehermant.github.io/anta_database][Documentation]] for quick start and further information.

* SQLite Database
The database uses SQLite for efficient indexing. Data is sourced from the associated DOIs and stored as binary DataFrame files for each layer (IRH) and trace ID. This structure enables:
- Browsing by author (region), layer age, or trace ID.
- Memory efficiency: Only relevant data is read when needed.
- Fast read performance: Lightweight and optimized for speed.
** Datasets currently included:
- Winter et al. 2018, (https://doi.org/10.1594/PANGAEA.895528)
- Cavitte et al. 2020, (https://doi.org/10.15784/601411)
- Beem et al. 2021, (https://doi.org/10.15784/601437)
- Wang et al. 2023, (https://doi.org/10.1594/PANGAEA.958462)
- Sanderson et al. 2024, (https://doi.org/10.5285/cfafb639-991a-422f-9caa-7793c195d316)
- Franke et al. 2025, (https://doi.org/10.1594/PANGAEA.973266)
* Key Features
- Efficient SQLite indexing
- Quick visualization on Antarctica map
- Generate lazy data for later use
* Installation
The Python module can be directly installed from [[https://pypi.org/project/anta-database/][PyPI]] with:
#+begin_src bash
pip install anta_database
#+end_src
Note that this module is new and under development, so that the [[https://pypi.org/project/anta-database/][PyPI]] package may not contain the latest features. For the latest version and development, see the instruction below.
To get started with the anta_database module, see the [[https://antoinehermant.github.io/anta_database][Documentation]].
Also, you need the actual data to use this module. It is currently not available on any public repository, so please contact me.

** Advanced installation
One can install the latest commit from this GitHub directory with:
#+begin_src bash
pip install git+https://github.com/antoinehermant/anta_database.git
#+end_src

Or for development, you should clone this repo and install the module in development mode:
#+begin_src bash
git clone git@github:antoinehermant/anta_database.git
pip install -e anta_database/
#+end_src

* Support and contact
You can email me for downloading the database: antoine.hermant@unibe.ch

Feel free to raise an issue on the GitHub if you find any bug or if you would like a feature added.
* Contribution
If you like this database and wish to help me develop this module, do not hesitate to contact me. You should then fork the repo, build feature branches and pull request. That would be much appreciated!
* Acknowledgment
I am developing this tool as part of my PhD project, which is funded by the Swiss National Science Foundation (grant no. 211542, Project CHARIBDIS)
Any data used through this database should be cited at source. For this, use the DOI provided in the metadata.
If you used this tool for your work and this was useful, please cite this repo, so other people get to know that it exists.
