name: anta-database-binder
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - ipykernel
  - jupyterlab
  - pip:
    - git+https://github.com/antoinehermant/anta_database.git  # Install from git
